#!/usr/bin/env python3
"""Render a taskify manifest set into the tasks.md that speckit expects.

Why this exists
---------------
This project replaced `/speckit-tasks` with `/taskify` (CLAUDE.md, "Spec-Kit
Adoption"). The workflow's `tasks` step became a gate that tells you to run
`/taskify` (.specify/workflows/speckit/workflow.yml). But the step right after
it, `speckit.implement`, still hard-requires `tasks.md`
(.claude/skills/speckit-implement/SKILL.md:60 ->
 .specify/scripts/bash/check-prerequisites.sh --require-tasks), so the chain
broke: /taskify writes task-manifests/, and implement refuses to start.

This script closes that gap WITHOUT creating a second source of truth. The
generated tasks.md is an ordered checklist that points at the manifests; every
task line carries the manifest path, so the implementing agent reads the real
contract (acceptance, invariants, forbidden_paths) from the YAML rather than
from the checklist. Same relationship as a build artifact to its source.

Blocked tasks are deliberately kept OUT of the executable phases and listed in a
separate, clearly non-executable section. speckit.implement walks the phases and
would otherwise start work whose external dependencies are not met.

Usage
-----
    python3 .specify/scripts/taskify_to_tasks_md.py <task-manifests-dir> [--out PATH]

Default output is <task-manifests-dir>/../tasks.md.
Re-run after every /taskify change; the file is generated, never hand-edited.

IMPORTANT for this repository — pass --out
------------------------------------------
The taskify default output directory is `.amplai/tasks/<feature-slug>/` whenever
the design source is NOT under `specs/<feature>/`. speckit, however, looks for
`tasks.md` inside the FEATURE_DIR that `.specify/scripts/bash/common.sh`
resolves (SPECIFY_FEATURE_DIRECTORY or .specify/feature.json). Those are two
different directories, so the default `<manifest_dir>/../tasks.md` would land in
`.amplai/tasks/tasks.md`, where speckit will never look. Always name the target:

    python3 .specify/scripts/taskify_to_tasks_md.py \
        .amplai/tasks/<feature-slug> --out specs/<feature>/tasks.md

Only when the manifests already live inside the feature directory (e.g.
`specs/<feature>/task-manifests/`) is the default correct.
"""
import argparse
import os
import sys

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML required. Install it with the project's normal "
          "dependency process (see .claude/skills/taskify/scripts/"
          "requirements.txt).", file=sys.stderr)
    raise SystemExit(2)

# Statuses whose tasks belong in the executable phases. Anything else is
# reported but not handed to an implementing agent.
RUNNABLE = ("ready", "in_progress", "verification", "needs_revalidation")
GENERATED_MARKER = "<!-- GENERATED BY .specify/scripts/taskify_to_tasks_md.py"


def load(path):
    with open(path, "r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def manifest_path(manifest_dir, task_id):
    return os.path.join(manifest_dir, "%s.yaml" % task_id)


def task_files(manifest):
    """allowed_paths is the honest 'which files does this touch' signal.

    speckit.implement uses file overlap to decide what may run together, so an
    empty list must stay empty rather than be guessed at."""
    return list((manifest.get("scope") or {}).get("allowed_paths") or [])


def required_commands(manifest):
    out = []
    for cmd in ((manifest.get("acceptance") or {}).get("commands") or []):
        if cmd.get("required") is True and cmd.get("run"):
            out.append(cmd["run"])
    return out


def render(index, manifests, manifest_dir, rel_base):
    idx_tasks = {t["id"]: t for t in index.get("tasks", [])}
    waves = (index.get("execution") or {}).get("waves") or []
    feature = index.get("feature") or {}
    src_files = [f.get("path") for f in (index.get("source") or {}).get("files", [])]

    lines = []
    lines.append("# Tasks: %s" % feature.get("title", feature.get("id", "FEATURE")))
    lines.append("")
    lines.append("%s -->" % GENERATED_MARKER)
    lines.append("<!-- DO NOT EDIT BY HAND. Source of truth is "
                 "task-manifests/index.yaml + the per-task YAML manifests. -->")
    lines.append("")
    lines.append("> **생성물이다. 직접 수정하지 않는다.**")
    lines.append("> 출처: `%s/index.yaml` 과 `%s/<ID>.yaml`."
                 % (rel_base, rel_base))
    lines.append("> 재생성: `python3 .specify/scripts/taskify_to_tasks_md.py %s`"
                 % rel_base)
    lines.append(">")
    lines.append("> 각 항목의 **계약은 manifest 에 있다** — acceptance behaviors, "
                 "invariants, forbidden_paths, loop/stop conditions. 구현 전에 "
                 "해당 YAML 을 읽는다. 이 체크리스트는 순서와 파일 소유만 전달한다.")
    lines.append("")

    if src_files:
        lines.append("**Design source**: " + ", ".join("`%s`" % p for p in src_files))
        lines.append("")

    runnable_ids = set()
    phase_no = 0
    for wave in waves:
        members = [tid for tid in wave.get("tasks", [])
                   if idx_tasks.get(tid, {}).get("status") in RUNNABLE]
        if not members:
            continue
        phase_no += 1
        lines.append("## Phase %d" % phase_no)
        note = wave.get("note")
        if note:
            lines.append("")
            lines.append("> %s" % " ".join(str(note).split()))
        lines.append("")
        # [P] only when the wave holds more than one runnable task AND no two of
        # them declare the same file. Same-wave is not by itself parallel-safe.
        parallel = len(members) > 1
        if parallel:
            seen = {}
            for tid in members:
                for path in task_files(manifests.get(tid, {})):
                    seen.setdefault(path, []).append(tid)
            if any(len(v) > 1 for v in seen.values()):
                parallel = False
        for tid in members:
            runnable_ids.add(tid)
            man = manifests.get(tid, {})
            meta = idx_tasks.get(tid, {})
            mark = " [P]" if parallel else ""
            lines.append("- [ ] %s%s %s" % (tid, mark, meta.get("title", "")))
            lines.append("  - manifest: `%s/%s.yaml`" % (rel_base, tid))
            deps = meta.get("depends_on") or []
            if deps:
                lines.append("  - depends on: %s" % ", ".join(deps))
            files = task_files(man)
            if files:
                lines.append("  - files: %s" % ", ".join("`%s`" % f for f in files))
            for run in required_commands(man):
                lines.append("  - verify: `%s`" % run)
        lines.append("")

    blocked = [t for t in index.get("tasks", []) if t.get("status") == "blocked"]
    if blocked:
        lines.append("## Blocked — DO NOT EXECUTE")
        lines.append("")
        lines.append("아래는 외부 의존이 안 풀려 실행 단계에 넣지 않았다. 의존이 풀리면 "
                     "manifest 의 status 를 바꾸고 이 파일을 재생성한다.")
        lines.append("")
        for meta in blocked:
            tid = meta["id"]
            man = manifests.get(tid, {})
            lines.append("- %s %s" % (tid, meta.get("title", "")))
            lines.append("  - manifest: `%s/%s.yaml`" % (rel_base, tid))
            for ext in ((man.get("dependencies") or {}).get("external") or []):
                lines.append("  - blocked by %s: %s"
                             % (ext.get("id", "EXT"), ext.get("name", "")))
        lines.append("")

    other = [t for t in index.get("tasks", [])
             if t["id"] not in runnable_ids and t.get("status") != "blocked"]
    if other:
        lines.append("## Not scheduled")
        lines.append("")
        for meta in other:
            lines.append("- %s (%s) %s"
                         % (meta["id"], meta.get("status"), meta.get("title", "")))
        lines.append("")

    oq = index.get("open_questions") or []
    if oq:
        lines.append("## Open questions")
        lines.append("")
        for q in oq:
            blocks = q.get("blocks") or []
            suffix = " — blocks %s" % ", ".join(blocks) if blocks else ""
            lines.append("- **%s** %s%s" % (q.get("id"), q.get("question"), suffix))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("manifest_dir", help="directory holding index.yaml and <ID>.yaml")
    ap.add_argument("--out", help="output path (default <manifest_dir>/../tasks.md)")
    args = ap.parse_args(argv)

    manifest_dir = os.path.abspath(args.manifest_dir)
    index_path = os.path.join(manifest_dir, "index.yaml")
    if not os.path.isfile(index_path):
        print("ERROR: index.yaml not found in %s" % manifest_dir, file=sys.stderr)
        return 1
    index = load(index_path)

    manifests = {}
    for meta in index.get("tasks", []):
        tid = meta["id"]
        path = manifest_path(manifest_dir, tid)
        if not os.path.isfile(path):
            print("ERROR: manifest missing for %s: %s" % (tid, path), file=sys.stderr)
            return 1
        manifests[tid] = load(path)

    out_path = args.out or os.path.join(os.path.dirname(manifest_dir), "tasks.md")
    out_path = os.path.abspath(out_path)

    # Never clobber a hand-written tasks.md. The marker is what proves this file
    # is ours to rewrite.
    if os.path.isfile(out_path):
        with open(out_path, "r", encoding="utf-8") as handle:
            head = handle.read(2048)
        if GENERATED_MARKER not in head:
            print("ERROR: %s exists and was not generated by this script. "
                  "Refusing to overwrite." % out_path, file=sys.stderr)
            return 1

    rel_base = os.path.relpath(manifest_dir, os.path.dirname(out_path))
    text = render(index, manifests, manifest_dir, rel_base)
    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write(text)
    print("wrote %s (%d task(s) from %s)"
          % (out_path, len(index.get("tasks", [])), index_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
