#!/usr/bin/env python3
"""Render a taskify manifest set into the tasks.md that speckit expects.

Why this exists
---------------
This project replaced `/speckit-tasks` with `/taskify` (CLAUDE.md, "Spec-Kit
Adoption"). The workflow's `tasks` step became a gate that tells you to run
`/taskify` (.specify/workflows/speckit/workflow.yml). But the step right after
it, `speckit.implement`, still hard-requires `tasks.md`
(.claude/skills/speckit-implement/SKILL.md:60 ->
 .specify/scripts/bash/check-prerequisites.sh --require-tasks), so the chain
broke: /taskify writes task-manifests/, and implement refuses to start.

This script closes that gap WITHOUT creating a second source of truth. The
generated tasks.md is an ordered checklist that points at the manifests; every
task line carries the manifest path, so the implementing agent reads the real
contract (acceptance, invariants, forbidden_paths) from the YAML rather than
from the checklist. Same relationship as a build artifact to its source.

Blocked tasks are deliberately kept OUT of the executable phases and listed in a
separate, clearly non-executable section. speckit.implement walks the phases and
would otherwise start work whose external dependencies are not met.

Usage
-----
    python3 .specify/scripts/taskify_to_tasks_md.py <task-manifests-dir> [--out PATH]

Default output is <task-manifests-dir>/../tasks.md.
Re-run after every /taskify change; the file is generated, never hand-edited.

IMPORTANT for this repository — pass --out
------------------------------------------
The taskify default output directory is `.amplai/tasks/<feature-slug>/` whenever
the design source is NOT under `specs/<feature>/`. speckit, however, looks for
`tasks.md` inside the FEATURE_DIR that `.specify/scripts/bash/common.sh`
resolves (SPECIFY_FEATURE_DIRECTORY or .specify/feature.json). Those are two
different directories, so the default `<manifest_dir>/../tasks.md` would land in
`.amplai/tasks/tasks.md`, where speckit will never look. Always name the target:

    python3 .specify/scripts/taskify_to_tasks_md.py \
        .amplai/tasks/<feature-slug> --out specs/<feature>/tasks.md

Only when the manifests already live inside the feature directory (e.g.
`specs/<feature>/task-manifests/`) is the default correct. The generated header
echoes back the exact command that reproduces the file, --out included.
"""
import argparse
import json
import os
import sys

# Statuses whose tasks belong in the executable phases. Anything else is
# reported but not handed to an implementing agent.
RUNNABLE = ("ready", "in_progress", "verification", "needs_revalidation")
GENERATED_MARKER = "<!-- GENERATED BY .specify/scripts/taskify_to_tasks_md.py"


def load(path):
    with open(path, "r", encoding="utf-8") as handle:
        text = handle.read()
    try:
        return json.loads(text)
    except ValueError:
        try:
            import yaml
        except ImportError:
            raise ValueError("Legacy YAML requires optional PyYAML; portable tasks use JSON.")
        return yaml.safe_load(text)


def manifest_path(manifest_dir, task_id):
    return os.path.join(manifest_dir, "%s.yaml" % task_id)


def task_files(manifest):
    """allowed_paths is the honest 'which files does this touch' signal.

    speckit.implement uses file overlap to decide what may run together, so an
    empty list must stay empty rather than be guessed at."""
    return list((manifest.get("scope") or {}).get("allowed_paths") or [])


def required_commands(manifest):
    out = []
    for cmd in ((manifest.get("acceptance") or {}).get("commands") or []):
        if cmd.get("required") is True and cmd.get("run"):
            out.append(cmd["run"])
    return out


def acceptance_lines(manifest):
    """Given/When/Then behaviors flattened to one line each.

    These are the human-readable half of the slice contract. The machine-checkable
    half is `Eval:`. Both are printed so a repair pass can tell "the behavior I was
    supposed to produce" apart from "the command that says whether I produced it"."""
    out = []
    for b in ((manifest.get("acceptance") or {}).get("behaviors") or []):
        if not isinstance(b, dict):
            out.append(str(b))
            continue
        bid = b.get("id")
        text = " ".join(
            str(b[k]).strip() for k in ("given", "when", "then") if b.get(k)
        )
        out.append("%s %s" % (bid, text) if bid else text)
    return out


def derive_slices(index, manifests):
    """Slice list for tasks.md, in priority order.

    1. `slices:` in index.yaml — taskify writes it when it can name a coherent
       functional unit. Authoritative.
    2. otherwise one slice per execution wave — waves are already the dependency
       tiers, so they are the least-wrong automatic grouping.

    Derived slices inherit goal/acceptance/eval from their member manifests. A
    slice with no eval command is emitted with an empty `Eval:` block on purpose:
    scripts/eval.sh then FAILS it loudly instead of silently passing a slice that
    nothing checks."""
    declared = index.get("slices") or []
    if declared:
        out = []
        for i, s in enumerate(declared, start=1):
            members = list(s.get("tasks") or [])
            evals = list(s.get("eval") or [])
            accepts = list(s.get("acceptance") or [])
            if not evals:
                for tid in members:
                    evals.extend(required_commands(manifests.get(tid, {})))
            if not accepts:
                for tid in members:
                    accepts.extend(acceptance_lines(manifests.get(tid, {})))
            out.append({
                "id": s.get("id") or "S%02d" % i,
                "title": s.get("title") or "",
                "goal": s.get("goal") or "",
                "tasks": members,
                "acceptance": dedupe(accepts),
                "eval": dedupe(evals),
                "depends_on": list(s.get("depends_on") or []),
            })
        return out

    out = []
    prev = None
    for i, wave in enumerate((index.get("execution") or {}).get("waves") or [],
                             start=1):
        members = list(wave.get("tasks") or [])
        sid = "S%02d" % i
        evals, accepts = [], []
        for tid in members:
            evals.extend(required_commands(manifests.get(tid, {})))
            accepts.extend(acceptance_lines(manifests.get(tid, {})))
        out.append({
            "id": sid,
            "title": (wave.get("title") or "Wave %d" % i),
            "goal": " ".join(str(wave.get("note") or "").split()),
            "tasks": members,
            "acceptance": dedupe(accepts),
            "eval": dedupe(evals),
            "depends_on": [prev] if prev else [],
        })
        prev = sid
    return out


def dedupe(items):
    seen, out = set(), []
    for it in items:
        if it not in seen:
            seen.add(it)
            out.append(it)
    return out


def regeneration_command(manifest_dir, out_path, repo_root):
    """The exact invocation that reproduces out_path.

    Must include --out whenever the default target (<manifest_dir>/../tasks.md)
    is not where the file actually goes; otherwise someone copies the header
    command, runs it, and silently writes tasks.md to a directory speckit never
    reads."""
    default_out = os.path.join(os.path.dirname(manifest_dir), "tasks.md")
    man = os.path.relpath(manifest_dir, repo_root)
    cmd = "python3 .specify/scripts/taskify_to_tasks_md.py %s" % man
    if os.path.abspath(default_out) != os.path.abspath(out_path):
        cmd += " --out %s" % os.path.relpath(out_path, repo_root)
    return cmd


def render(index, manifests, manifest_dir, rel_base, regen_cmd):
    idx_tasks = {t["id"]: t for t in index.get("tasks", [])}
    feature = index.get("feature") or {}
    src_files = [f.get("path") for f in (index.get("source") or {}).get("files", [])]

    lines = []
    lines.append("# Tasks: %s" % feature.get("title", feature.get("id", "FEATURE")))
    lines.append("")
    lines.append("%s -->" % GENERATED_MARKER)
    lines.append("<!-- DO NOT EDIT BY HAND. Source of truth is "
                 "%s/index.yaml + the per-task YAML manifests. -->" % rel_base)
    lines.append("")
    lines.append("> **생성물이다. 직접 수정하지 않는다.**")
    lines.append("> 출처: `%s/index.yaml` 과 `%s/<ID>.yaml`."
                 % (rel_base, rel_base))
    lines.append("> 재생성 (repo root 에서): `%s`" % regen_cmd)
    lines.append(">")
    lines.append("> 각 항목의 **계약은 manifest 에 있다** — acceptance behaviors, "
                 "invariants, forbidden_paths, loop/stop conditions. 구현 전에 "
                 "해당 YAML 을 읽는다. 이 체크리스트는 순서와 파일 소유만 전달한다.")
    lines.append(">")
    lines.append("> **Slice 단위로 돈다.** slice 하나 = implement/eval 루프 한 바퀴.")
    lines.append("> `Eval:` 의 명령이 그 slice 의 유일한 합격 판정이다:")
    lines.append("> `scripts/eval.sh --slice <ID>` — exit 0 이면 PASS, 아니면 FAIL.")
    lines.append("")

    if src_files:
        lines.append("**Design source**: " + ", ".join("`%s`" % p for p in src_files))
        lines.append("")

    runnable_ids = set()
    for sl in derive_slices(index, manifests):
        members = [tid for tid in sl["tasks"]
                   if idx_tasks.get(tid, {}).get("status") in RUNNABLE]
        if not members:
            continue
        title = sl["title"]
        lines.append("## Slice %s%s" % (sl["id"], " — %s" % title if title else ""))
        lines.append("")

        lines.append("Goal:")
        goal = sl["goal"] or (idx_tasks.get(members[0], {}).get("title") or "")
        lines.append("- %s" % (goal or "(manifest 의 goal 을 따른다)"))
        lines.append("")

        # [P] only when the slice holds more than one runnable task, no two of
        # them declare the same file, AND none depends on another member. Being
        # in the same slice is not by itself parallel-safe — grouping is about a
        # shared acceptance boundary, not about independence.
        parallel = len(members) > 1
        if parallel:
            seen = {}
            for tid in members:
                for path in task_files(manifests.get(tid, {})):
                    seen.setdefault(path, []).append(tid)
            if any(len(v) > 1 for v in seen.values()):
                parallel = False
        if parallel:
            inside = set(members)
            for tid in members:
                if inside & set(idx_tasks.get(tid, {}).get("depends_on") or []):
                    parallel = False
                    break

        lines.append("Tasks:")
        for tid in members:
            runnable_ids.add(tid)
            man = manifests.get(tid, {})
            meta = idx_tasks.get(tid, {})
            mark = " [P]" if parallel else ""
            lines.append("- [ ] %s%s %s" % (tid, mark, meta.get("title", "")))
            lines.append("  - manifest: `%s/%s.yaml`" % (rel_base, tid))
            deps = meta.get("depends_on") or []
            if deps:
                lines.append("  - depends on: %s" % ", ".join(deps))
            files = task_files(man)
            if files:
                lines.append("  - files: %s" % ", ".join("`%s`" % f for f in files))
        lines.append("")

        lines.append("Acceptance:")
        if sl["acceptance"]:
            for a in sl["acceptance"]:
                lines.append("- %s" % a)
        else:
            lines.append("- (manifest 에 acceptance behavior 가 없다 — /taskify 로 채운다)")
        lines.append("")

        # 빈 Eval 은 고의로 빈 채로 낸다. scripts/eval.sh 가 이걸 FAIL 로 잡아야
        # "아무도 안 보는 slice 가 조용히 통과하는" 경로가 안 생긴다.
        lines.append("Eval:")
        for cmd in sl["eval"]:
            lines.append("- `%s`" % cmd)
        lines.append("")

        lines.append("Dependencies:")
        if sl["depends_on"]:
            for d in sl["depends_on"]:
                lines.append("- %s" % d)
        else:
            lines.append("- none")
        lines.append("")

    blocked = [t for t in index.get("tasks", []) if t.get("status") == "blocked"]
    if blocked:
        lines.append("## Blocked — DO NOT EXECUTE")
        lines.append("")
        lines.append("아래는 외부 의존이 안 풀려 실행 단계에 넣지 않았다. 의존이 풀리면 "
                     "manifest 의 status 를 바꾸고 이 파일을 재생성한다.")
        lines.append("")
        for meta in blocked:
            tid = meta["id"]
            man = manifests.get(tid, {})
            lines.append("- %s %s" % (tid, meta.get("title", "")))
            lines.append("  - manifest: `%s/%s.yaml`" % (rel_base, tid))
            for ext in ((man.get("dependencies") or {}).get("external") or []):
                lines.append("  - blocked by %s: %s"
                             % (ext.get("id", "EXT"), ext.get("name", "")))
        lines.append("")

    other = [t for t in index.get("tasks", [])
             if t["id"] not in runnable_ids and t.get("status") != "blocked"]
    if other:
        lines.append("## Not scheduled")
        lines.append("")
        for meta in other:
            lines.append("- %s (%s) %s"
                         % (meta["id"], meta.get("status"), meta.get("title", "")))
        lines.append("")

    oq = index.get("open_questions") or []
    if oq:
        lines.append("## Open questions")
        lines.append("")
        for q in oq:
            blocks = q.get("blocks") or []
            suffix = " — blocks %s" % ", ".join(blocks) if blocks else ""
            lines.append("- **%s** %s%s" % (q.get("id"), q.get("question"), suffix))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("manifest_dir", help="directory holding index.yaml and <ID>.yaml")
    ap.add_argument("--out", help="output path (default <manifest_dir>/../tasks.md)")
    args = ap.parse_args(argv)

    manifest_dir = os.path.abspath(args.manifest_dir)
    index_path = os.path.join(manifest_dir, "index.yaml")
    if not os.path.isfile(index_path):
        print("ERROR: index.yaml not found in %s" % manifest_dir, file=sys.stderr)
        return 1
    index = load(index_path)

    manifests = {}
    for meta in index.get("tasks", []):
        tid = meta["id"]
        path = manifest_path(manifest_dir, tid)
        if not os.path.isfile(path):
            print("ERROR: manifest missing for %s: %s" % (tid, path), file=sys.stderr)
            return 1
        manifests[tid] = load(path)

    out_path = args.out or os.path.join(os.path.dirname(manifest_dir), "tasks.md")
    out_path = os.path.abspath(out_path)

    # Never clobber a hand-written tasks.md. The marker is what proves this file
    # is ours to rewrite.
    if os.path.isfile(out_path):
        with open(out_path, "r", encoding="utf-8") as handle:
            head = handle.read(2048)
        if GENERATED_MARKER not in head:
            print("ERROR: %s exists and was not generated by this script. "
                  "Refusing to overwrite." % out_path, file=sys.stderr)
            return 1

    rel_base = os.path.relpath(manifest_dir, os.path.dirname(out_path))
    repo_root = os.getcwd()
    regen_cmd = regeneration_command(manifest_dir, out_path, repo_root)
    text = render(index, manifests, manifest_dir, rel_base, regen_cmd)
    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write(text)
    print("wrote %s (%d task(s) from %s)"
          % (out_path, len(index.get("tasks", [])), index_path))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ValueError, OSError) as exc:
        print("ERROR: %s" % exc, file=sys.stderr)
        raise SystemExit(1)
