"""Stable validation codes for Proposal project boundaries."""

PROPOSAL_SOURCE_PROJECT_MISMATCH = "PROPOSAL_SOURCE_PROJECT_MISMATCH"
PROPOSAL_EVIDENCE_PROJECT_MISMATCH = "PROPOSAL_EVIDENCE_PROJECT_MISMATCH"
PROPOSAL_TARGET_PROJECT_MISMATCH = "PROPOSAL_TARGET_PROJECT_MISMATCH"
PROPOSAL_DRAFT_PROJECT_MISMATCH = "PROPOSAL_DRAFT_PROJECT_MISMATCH"
PROPOSAL_DRAFT_NAMESPACE_MISMATCH = "PROPOSAL_DRAFT_NAMESPACE_MISMATCH"
