"""Build deterministic review Proposals from gated semantic comparisons."""

from __future__ import annotations

import hashlib
from datetime import datetime
from pathlib import Path

import yaml

from amplai_foundry.domain.enums import MemoryKind, MemoryStatus
from amplai_foundry.domain.models import MemoryObject
from amplai_foundry.ingestion.identifiers import safe_slug
from amplai_foundry.lint.rules.schema import KIND_DIRECTORIES
from amplai_foundry.projects.repository import ProjectPack
from amplai_foundry.proposals.models import (
    Confidence,
    EvidenceLocator,
    OperationType,
    Proposal,
    ProposalEvidence,
    ProposalOperation,
    proposal_id,
)
from amplai_foundry.proposals.repository import ProposalRepository
from amplai_foundry.repositories.markdown import MarkdownMemoryRepository
from amplai_foundry.semantics.models import (
    ComparisonRelation,
    ComparisonResult,
    KnowledgeCandidate,
)

_PREFIX_BY_KIND = {
    MemoryKind.CONCEPT: "CON",
    MemoryKind.PRINCIPLE: "PRI",
    MemoryKind.DECISION: "DEC",
    MemoryKind.QUESTION: "QUE",
    MemoryKind.ARCHITECTURE: "ARC",
    MemoryKind.EXPERIMENT: "EXP",
}
_DIRECTORY_BY_KIND = {kind: directory for directory, kind in KIND_DIRECTORIES.items()}


class IntakeProposalBuilder:
    def build(
        self,
        *,
        pack: ProjectPack,
        candidates: list[KnowledgeCandidate],
        comparisons: list[ComparisonResult],
        created_at: datetime,
        created_by: str,
    ) -> tuple[Proposal | None, Path | None]:
        by_candidate = {item.candidate_id: item for item in comparisons}
        actionable = [
            candidate
            for candidate in candidates
            if by_candidate[candidate.candidate_id].relation
            in {
                ComparisonRelation.NEW,
                ComparisonRelation.REFINES,
                ComparisonRelation.CONFLICTS,
                ComparisonRelation.SEMANTIC_DUPLICATE,
                ComparisonRelation.EXACT_DUPLICATE,
            }
        ]
        if not actionable:
            return None, None
        seed = hashlib.sha256(
            "\0".join(
                f"{item.candidate_id}:{by_candidate[item.candidate_id].relation.value}"
                for item in actionable
            ).encode()
        ).hexdigest()
        identifier = proposal_id(created_at.date(), seed)
        proposal_repository = ProposalRepository(pack.proposal_root)
        proposal_dir = proposal_repository.path_for(identifier).parent
        memory_repository = MarkdownMemoryRepository(pack.memory_root)
        allocated: set[str] = set()
        operations: list[ProposalOperation] = []
        for index, candidate in enumerate(actionable, start=1):
            comparison = by_candidate[candidate.candidate_id]
            operation = self._operation(
                pack=pack,
                proposal_dir=proposal_dir,
                memory_repository=memory_repository,
                candidate=candidate,
                comparison=comparison,
                operation_id=f"OP-{index:03d}",
                created_at=created_at,
                allocated=allocated,
            )
            if operation is not None:
                operations.append(operation)
        if not operations:
            return None, None
        source_ids = sorted(
            {
                evidence.source.local_id
                for candidate in actionable
                for evidence in candidate.evidence
            }
        )
        proposal = Proposal(
            proposal_id=identifier,
            project=pack.manifest.project_id,
            namespace=pack.manifest.namespace,
            source_ids=source_ids,
            created_at=created_at,
            created_by=created_by,
            operations=operations,
            notes=[
                "Generated by Knowledge Intake; no authoritative change was auto-applied.",
                "Comparison policy output is preserved in the corresponding IntakeRun.",
            ],
        )
        path = proposal_repository.save(proposal)
        return proposal, path

    def _operation(
        self,
        *,
        pack: ProjectPack,
        proposal_dir: Path,
        memory_repository: MarkdownMemoryRepository,
        candidate: KnowledgeCandidate,
        comparison: ComparisonResult,
        operation_id: str,
        created_at: datetime,
        allocated: set[str],
    ) -> ProposalOperation | None:
        evidence = [
            ProposalEvidence(
                source_id=item.source.local_id,
                locator=EvidenceLocator(start=item.start_line, end=item.end_line),
            )
            for item in candidate.evidence
        ]
        kind = candidate.suggested_kinds[0]
        if comparison.relation is ComparisonRelation.CONFLICTS:
            conflict_target = (
                comparison.matched_target_refs[0] if comparison.matched_target_refs else None
            )
            if conflict_target is None:
                return None
            return ProposalOperation(
                operation_id=operation_id,
                type=OperationType.CONFLICT,
                target_id=conflict_target.local_id,
                kind=kind.value,
                title=candidate.canonical_statement[:120],
                reason="Semantic comparison detected an authoritative conflict.",
                evidence=evidence,
                confidence=Confidence.HIGH,
            )
        if comparison.relation is ComparisonRelation.NEW:
            target_id = self._allocate_id(memory_repository, kind, pack, allocated)
            draft = self._new_memory(candidate, target_id, kind, created_at)
            draft_path = self._write_draft(pack, proposal_dir, draft)
            return ProposalOperation(
                operation_id=operation_id,
                type=OperationType.CREATE,
                kind=kind.value,
                title=draft.title,
                reason="No project-scoped semantic match was found.",
                evidence=evidence,
                confidence=Confidence.HIGH,
                draft_path=f"drafts/{draft_path.name}",
            )
        if comparison.relation is ComparisonRelation.REFINES:
            target_ref = (
                comparison.matched_target_refs[0] if comparison.matched_target_refs else None
            )
            if target_ref is None:
                return None
            target_memory = memory_repository.get(target_ref)
            if target_memory is None:
                return None
            target_path = Path(memory_repository.path_for(target_memory.ref))
            draft = target_memory.model_copy(
                update={
                    "updated_at": created_at.date(),
                    "revision": target_memory.revision + 1,
                    "summary": candidate.canonical_statement,
                    "source_refs": sorted(
                        {
                            *target_memory.source_refs,
                            *(item.source.local_id for item in candidate.evidence),
                        }
                    ),
                    "semantic": candidate.descriptor(),
                    "content": (
                        target_memory.content.rstrip()
                        + "\n\n## Proposed Refinement\n\n"
                        + candidate.canonical_statement
                        + "\n"
                    ),
                }
            )
            draft_path = self._write_draft(pack, proposal_dir, draft)
            return ProposalOperation(
                operation_id=operation_id,
                type=OperationType.UPDATE,
                target_id=target_memory.id,
                kind=target_memory.kind.value,
                title=target_memory.title,
                reason="Incoming evidence adds constraints to the matched meaning.",
                evidence=evidence,
                confidence=Confidence.HIGH,
                draft_path=f"drafts/{draft_path.name}",
                expected_revision=target_memory.revision,
                expected_target_sha256=hashlib.sha256(target_path.read_bytes()).hexdigest(),
            )
        if comparison.relation in {
            ComparisonRelation.EXACT_DUPLICATE,
            ComparisonRelation.SEMANTIC_DUPLICATE,
        }:
            target_ref = (
                comparison.matched_target_refs[0] if comparison.matched_target_refs else None
            )
            if target_ref is None:
                return None
            target_memory = memory_repository.get(target_ref)
            if target_memory is None:
                return None
            target_path = Path(memory_repository.path_for(target_memory.ref))
            linked_sources = sorted(
                {
                    *target_memory.source_refs,
                    *(item.source.local_id for item in candidate.evidence),
                }
            )
            if linked_sources == target_memory.source_refs:
                return None
            draft = target_memory.model_copy(
                update={
                    "updated_at": created_at.date(),
                    "revision": target_memory.revision + 1,
                    "source_refs": linked_sources,
                }
            )
            draft_path = self._write_draft(pack, proposal_dir, draft)
            return ProposalOperation(
                operation_id=operation_id,
                type=OperationType.LINK,
                target_id=target_memory.id,
                kind=target_memory.kind.value,
                title=target_memory.title,
                reason="Independent duplicate evidence is linked without changing meaning.",
                evidence=evidence,
                confidence=Confidence.HIGH,
                draft_path=f"drafts/{draft_path.name}",
                expected_revision=target_memory.revision,
                expected_target_sha256=hashlib.sha256(target_path.read_bytes()).hexdigest(),
            )
        return None

    @staticmethod
    def _allocate_id(
        repository: MarkdownMemoryRepository,
        kind: MemoryKind,
        pack: ProjectPack,
        allocated: set[str],
    ) -> str:
        prefix = _PREFIX_BY_KIND[kind]
        used = {
            memory.id
            for memory in repository.list(namespace=pack.manifest.namespace)
            if memory.kind is kind
        } | allocated
        numbers = [
            int(identifier.split("-", 1)[1])
            for identifier in used
            if identifier.startswith(f"{prefix}-") and identifier.split("-", 1)[1].isdigit()
        ]
        identifier = f"{prefix}-{(max(numbers, default=0) + 1):04d}"
        allocated.add(identifier)
        return identifier

    @staticmethod
    def _new_memory(
        candidate: KnowledgeCandidate,
        target_id: str,
        kind: MemoryKind,
        created_at: datetime,
    ) -> MemoryObject:
        title = candidate.canonical_statement[:120]
        return MemoryObject(
            id=target_id,
            namespace=candidate.project.namespace,
            project=candidate.project.project_id,
            kind=kind,
            status=MemoryStatus.CANDIDATE,
            title=title,
            summary=candidate.canonical_statement,
            created_at=created_at.date(),
            updated_at=created_at.date(),
            source_refs=sorted({item.source.local_id for item in candidate.evidence}),
            relations=[],
            revision=1,
            tags=["semantic-candidate"],
            semantic=candidate.descriptor(),
            content=(
                f"# {title}\n\n## Claim\n\n{candidate.canonical_statement}\n\n"
                "## Governance\n\nThis draft requires explicit review before canonical apply.\n"
            ),
        )

    @staticmethod
    def _write_draft(pack: ProjectPack, proposal_dir: Path, draft: MemoryObject) -> Path:
        drafts = proposal_dir / "drafts"
        drafts.mkdir(parents=True, exist_ok=True)
        path = drafts / f"{draft.id}-{safe_slug(draft.title)}.md"
        metadata = draft.model_dump(
            mode="json",
            exclude={"content"},
            exclude_none=True,
        )
        front_matter = yaml.safe_dump(
            metadata,
            allow_unicode=True,
            sort_keys=False,
        )
        path.write_text(f"---\n{front_matter}---\n{draft.content}", encoding="utf-8")
        path.resolve().relative_to(pack.root.resolve())
        return path
